name: 'ABC to PDF'
description: 'Converts sheet music from ABC format to PDF'
author: 'PennRobotics'
inputs:
  overwrite:
    description: 'Overwrite existing PDFs'
    default: true
    # Small changes to tunes should result in new output files
    # `git pull` should discard the unchanged files
  # TODO: others here
branding:
  icon: 'music'
  # alternate: book-open, file-text, layers, pen-tool, printer, type, zap
  color: 'green'
runs:
  using: 'composite'
  steps:
    - run: echo TEST
