name: abc2pdf

on:
  workflow_dispatch
  #schedule
  #  - cron: '0 0 * * *'  # daily
  #push:
  #  branches: [ "main" ]

jobs:
  checkforbinary:
    runs-on: ubuntu-latest
    outputs:
      needscompiling: ${{ steps.decision.outputs.needscompiling }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Save SHA for present-day abcm2ps repository for comparison
        run: git ls-remote https://github.com/lewdlime/abcm2ps.git HEAD | cut -f1 > submodule-sha-cmp.txt

      - name: Output to log if converter does not exist
        run: |
          [ ! -e "converter/abcm2ps.js" ] &&
          { echo Converter not found and should be now compiled; rm -f submodule-sha.txt; }

      - name: If SHA does not match or does not exist, compile and write current SHA to repo
        id: decision
        run: |
          diff -N -q submodule-sha-cmp.txt submodule-sha.txt > /dev/null &&
          { echo "Compiled binary uses latest source"; echo "needscompiling=false" >> $GITHUB_OUTPUT; } ||
          { echo "Building binary"; echo "needscompiling=true" >> $GITHUB_OUTPUT; }

  compile:
    runs-on: ubuntu-latest
    needs: checkforbinary
    env:
      NEEDSCOMPILING: ${{ needs.checkforbinary.outputs.needscompiling }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: emscripten

      - name: configure
        run: |
          [ "$NEEDSCOMPILING" = "true" ] && cd abcm2ps && emconfigure ./configure || echo Skipping step 

      - name: make
        run: |
          [ "$NEEDSCOMPILING" = "true" ] && emmake -C abcm2ps CFLAGS=-DA4_FORMAT=1 || echo Skipping step 
        
      - name: move compiled abcm2ps files (wasm/js) out of submodule directory
        run: |
          [ "$NEEDSCOMPILING" = "true" ] && mkdir -p converter && mv abcm2ps/abcm2ps.* converter/ || echo Skipping step 

      # TODO: how to call abcm2ps.js with arguments?
      #- name: create version snippet
      #  run: |
      #    [ "$NEEDSCOMPILING" = "true" ] && converter/abcm2ps.js -V > converter/version.txt || echo Skipping step 

      - name: Save SHA from abcm2ps repository
        run: |
          [ "$NEEDSCOMPILING" = "true" ] && git ls-remote https://github.com/lewdlime/abcm2ps.git HEAD | cut -f1 > submodule-sha.txt || echo Skipping step 

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit compiled abcm2ps (A4 output)
          file_pattern: 'converter/abcm2ps converter/version.txt submodule-sha.txt'

  convert:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ghostscript

      - run: |
          [ -d in ] && [ ! -d out ] && mkdir -p out || echo "Note: No input or output dir already exists"

      - run: |
          for abcfile in in/*.abc; do \
              [ -e "out/`basename $abcfile .abc`.pdf" ] && continue; \
              converter/abcm2ps -F format/thinlines.fmt -F format/newheads.fmt $abcfile; \
              ps2pdf Out.ps "out/`basename $abcfile .abc`.pdf"; \
              rm Out.ps; \
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated PDF
