name: Convert ABC to PDF

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  abctopdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          [ ! -e converter/abcm2ps ] && echo "Converter not compiled"

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ghostscript
      - run: chmod +x converter/abcm2ps
      - run: mkdir -p out
      - run: |
          for abcfile in in/*.abc; do \
              [ -e "out/`basename $abcfile .abc`.pdf" ] && continue; \
              converter/abcm2ps $abcfile; \
              ps2pdf Out.ps "out/`basename $abcfile .abc`.pdf"; \
              rm Out.ps; \
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated PDF
