name: Check if submodule is updated

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save SHA for present-day abcm2ps repository for comparison
        run: git ls-remote https://github.com/lewdlime/abcm2ps.git HEAD | cut -f1 > submodule-sha-cmp.txt

      - name: If SHA does not match or does not exist, compile and write current SHA to repo
        run: |
          diff -N -q submodule-sha-cmp.txt submodule-sha.txt > /dev/null &&
          echo Compiled binary uses latest source ||
          {
            echo make
            echo cp submodule-sha-cmp.txt submodule-sha.txt
            cat submodule-sha-cmp.txt
          }
        # TODO-debug: remove `cat ...`

      # TODO: commit compiled binary and SHA
