name: abc2pdf

on:
  push:
    branches: [ "main" ]

jobs:
  checkforbinary:
    runs-on: ubuntu-latest
    outputs:
      needscompiling: ${{ steps.decision.outputs.needscompiling }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ghostscript build-essential

      - name: Save SHA for present-day abcm2ps repository for comparison
        run: git ls-remote https://github.com/lewdlime/abcm2ps.git HEAD | cut -f1 > submodule-sha-cmp.txt

      - name: Output to log if converter does not exist
        run: |
          [ ! -e "converter/abcm2ps" ] &&
          echo Converter not found and should be now compiled ||
          chmod +x converter/abcm2ps

      - name: If SHA does not match or does not exist, compile and write current SHA to repo
        id: decision
        run: |
          diff -N -q submodule-sha-cmp.txt submodule-sha.txt > /dev/null ||
          { echo "Building binary"; echo "needscompiling=true" >> $GITHUB_OUTPUT } &&
          { echo "Compiled binary uses latest source"; echo "needscompiling=false" >> $GITHUB_OUTPUT }

  compile:
    runs-on: ubuntu-latest
    needs: checkforbinary
    steps:
      - env:
          NEEDSCOMPILING: ${{ needs.checkforbinary.outputs.needscompiling }}
        run: |
          [ "$NEEDSCOMPILING" = "false" ] || exit 0

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: configure
        run: cd abcm2ps && ./configure

      - name: make
        run: make -C abcm2ps CFLAGS=-DA4_FORMAT=1
        
      - name: move abcm2ps out of submodule directory
        run: mkdir -p converter && mv abcm2ps/abcm2ps converter/

      - name: create version snippet
        run: converter/abcm2ps -V > converter/version.txt

      - name: save SHA from abcm2ps repo
        run: cp submodule-sha-cmp.txt submodule-sha.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit compiled abcm2ps (A4 output)
          file_pattern: 'converter/abcm2ps converter/version.txt submodule-sha.txt'

  convert:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for abcfile in in/*.abc; do \
              [ -e "out/`basename $abcfile .abc`.pdf" ] && continue; \
              converter/abcm2ps $abcfile; \
              ps2pdf Out.ps "out/`basename $abcfile .abc`.pdf"; \
              rm Out.ps; \
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated PDF
